version: '3.9'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: .env
  web:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
    entrypoint: ./entrypoint-app.sh
  worker:
    depends_on:
      - web
      - db
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    volumes:
      - .:/app
    env_file: .env
    entrypoint: ./entrypoint-worker.sh
  redis:
    image: 'redis:7-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  redis:
  postgres:



