version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: .env
  web:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    environment:
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5

volumes:
  postgres:



