default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL") { '' } %> # This is the line we added
development:
  <<: *default
  database: onecsv_development
test:
  <<: *default
  database: onecsv_test
production:
  <<: *default
  database: onecsv_production
  username: onecsv
  password: <%= ENV["ONECSV_DATABASE_PASSWORD"] %>